theme: jekyll-theme-cayman
# Site settings
title: Alphonse's Blog    				  	#你博客的标题
SEOTitle: Alphonse's Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img:  img/post-bg-rwd.jpg 	#显示在首页的背景图片
email: 953688086@qq.com	
description: "Alphonse's Blog"  			 #网站介绍
keyword: "Blog" #关键词
url: "https://cn-Alphonse.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "铁废物"
#sidebar-avatar:      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
# Disqus settings（https://disqus.com/）
#disqus_username: cn-Alphonse
